package MessageApp;


/**
* MessageApp/DogHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Message.idl
* Monday, September 15, 2025 1:10:38 PM ICT
*/

abstract public class DogHelper
{
  private static String  _id = "IDL:MessageApp/Dog:1.0";

  public static void insert (org.omg.CORBA.Any a, MessageApp.Dog that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static MessageApp.Dog extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (MessageApp.DogHelper.id (), "Dog");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static MessageApp.Dog read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_DogStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, MessageApp.Dog value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static MessageApp.Dog narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof MessageApp.Dog)
      return (MessageApp.Dog)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      MessageApp._DogStub stub = new MessageApp._DogStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static MessageApp.Dog unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof MessageApp.Dog)
      return (MessageApp.Dog)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      MessageApp._DogStub stub = new MessageApp._DogStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
