package MessageApp;

/**
* MessageApp/DogHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Message.idl
* Monday, September 15, 2025 1:10:38 PM ICT
*/

public final class DogHolder implements org.omg.CORBA.portable.Streamable
{
  public MessageApp.Dog value = null;

  public DogHolder ()
  {
  }

  public DogHolder (MessageApp.Dog initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = MessageApp.DogHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    MessageApp.DogHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return MessageApp.DogHelper.type ();
  }

}
