package MessageApp;


/**
* MessageApp/DogOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Message.idl
* Monday, September 15, 2025 1:10:38 PM ICT
*/

public interface DogOperations 
{
  void setDog (String name, String kind, String hairColor, int age);

  // Thu�"c tính (getter/setter)
  String getName ();
  void setName (String name);
  String getKind ();
  void setKind (String kind);
  String getHairColor ();
  void setHairColor (String color);
  int getAge ();
  void setAge (int age);

  // Hành vi
  String bark ();
  String walk ();
  String playCatch (String item);
} // interface DogOperations
