package MessageApp;


/**
* MessageApp/DogPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Message.idl
* Monday, September 15, 2025 1:10:38 PM ICT
*/

public abstract class DogPOA extends org.omg.PortableServer.Servant
 implements MessageApp.DogOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("setDog", new java.lang.Integer (0));
    _methods.put ("getName", new java.lang.Integer (1));
    _methods.put ("setName", new java.lang.Integer (2));
    _methods.put ("getKind", new java.lang.Integer (3));
    _methods.put ("setKind", new java.lang.Integer (4));
    _methods.put ("getHairColor", new java.lang.Integer (5));
    _methods.put ("setHairColor", new java.lang.Integer (6));
    _methods.put ("getAge", new java.lang.Integer (7));
    _methods.put ("setAge", new java.lang.Integer (8));
    _methods.put ("bark", new java.lang.Integer (9));
    _methods.put ("walk", new java.lang.Integer (10));
    _methods.put ("playCatch", new java.lang.Integer (11));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // MessageApp/Dog/setDog
       {
         String name = in.read_string ();
         String kind = in.read_string ();
         String hairColor = in.read_string ();
         int age = in.read_long ();
         this.setDog (name, kind, hairColor, age);
         out = $rh.createReply();
         break;
       }


  // Thu�"c tính (getter/setter)
       case 1:  // MessageApp/Dog/getName
       {
         String $result = null;
         $result = this.getName ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 2:  // MessageApp/Dog/setName
       {
         String name = in.read_string ();
         this.setName (name);
         out = $rh.createReply();
         break;
       }

       case 3:  // MessageApp/Dog/getKind
       {
         String $result = null;
         $result = this.getKind ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 4:  // MessageApp/Dog/setKind
       {
         String kind = in.read_string ();
         this.setKind (kind);
         out = $rh.createReply();
         break;
       }

       case 5:  // MessageApp/Dog/getHairColor
       {
         String $result = null;
         $result = this.getHairColor ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 6:  // MessageApp/Dog/setHairColor
       {
         String color = in.read_string ();
         this.setHairColor (color);
         out = $rh.createReply();
         break;
       }

       case 7:  // MessageApp/Dog/getAge
       {
         int $result = (int)0;
         $result = this.getAge ();
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 8:  // MessageApp/Dog/setAge
       {
         int age = in.read_long ();
         this.setAge (age);
         out = $rh.createReply();
         break;
       }


  // Hành vi
       case 9:  // MessageApp/Dog/bark
       {
         String $result = null;
         $result = this.bark ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 10:  // MessageApp/Dog/walk
       {
         String $result = null;
         $result = this.walk ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 11:  // MessageApp/Dog/playCatch
       {
         String item = in.read_string ();
         String $result = null;
         $result = this.playCatch (item);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:MessageApp/Dog:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Dog _this() 
  {
    return DogHelper.narrow(
    super._this_object());
  }

  public Dog _this(org.omg.CORBA.ORB orb) 
  {
    return DogHelper.narrow(
    super._this_object(orb));
  }


} // class DogPOA
