package MessageApp;


/**
* MessageApp/MessageOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Message.idl
* Monday, September 15, 2025 1:10:38 PM ICT
*/

public interface MessageOperations 
{
  String send (String msg);
} // interface MessageOperations
