package MessageApp;

/**
* MessageApp/MessageHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Message.idl
* Monday, September 15, 2025 1:10:38 PM ICT
*/

public final class MessageHolder implements org.omg.CORBA.portable.Streamable
{
  public MessageApp.Message value = null;

  public MessageHolder ()
  {
  }

  public MessageHolder (MessageApp.Message initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = MessageApp.MessageHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    MessageApp.MessageHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return MessageApp.MessageHelper.type ();
  }

}
